name: Java CI with Maven (JDK 19)

# Trigger on push or pull request to main branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 19
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build project
      - name: Build with Maven
        run: mvn clean install --batch-mode -DskipTests

      # Step 5: Run tests
      - name: Run tests
        run: mvn test --batch-mode -DskipTests

      # Step 6: Upload JAR artifact
      - name: Upload core-banking-service JAR
        uses: actions/upload-artifact@v4
        with:
          name: core-banking
          path: core-banking/target/*.jar
